### ISSUE TITLE
External Unwrap Bugs/Projects

### ISSUE THREAD

**Issue by Merker6** [Community-A-4E/community-a4e-c#603]
This is a consolidation of all existing unwrap needs for the external model

**Unwrap Checklist**
- [x] Canopy Unwrap Issues (Fig. 1) #257 
- [ ] Body Unwrap Issues (Fig. 2-4) #216 
- [x] Speedbrake Unwrap Move (Fig. 5) #473 
- [x] Tailhook Base - New Unwrap (Fig. 6) #602 
- [x] Wheel Well Launch Hooks - New Unwraps (Fig. 7) #478 

**Fig. 1**
![image](https://github.com/heclak/community-a4e-c/assets/16724430/8767e84e-ab78-48fa-bc60-42dcd74e6bdd)

**Fig. 2**
![image](https://github.com/heclak/community-a4e-c/assets/16724430/76830459-2a80-4d37-a74d-d7a21c36809c)

**Fig. 3**
![image](https://github.com/heclak/community-a4e-c/assets/16724430/446e5f07-945d-4b5e-a640-4b031e2d8f1d)

**Fig. 4**
![image](https://github.com/heclak/community-a4e-c/assets/16724430/5b4e8f95-d086-4b89-8bc3-f52e3f07cabb)

**Fig. 5**
![image](https://github.com/heclak/community-a4e-c/assets/16724430/47bb2625-1ff5-4799-acc8-d8cf77ab4411)

**Fig. 6**
![image](https://github.com/heclak/community-a4e-c/assets/16724430/ad2993b3-e27f-43b2-a738-8341ad1d2101)

**Fig. 7**
![image](https://github.com/heclak/community-a4e-c/assets/16724430/e1b5cd8d-c3d8-487c-b27a-59d5f2204d18)

**Comment by Merker6** [comment]
Please note that this is an aggregation of a number of previous, individual issues. I provided commentary on all of them if there are further questions or in need of reference

**Comment by callmepartario** [comment]
Binaries are updated with Merker's updated model. Here is what he reports is accomplished.

- [x] Canopy UV Map Adjusted
- [x] Speedbrake UV Map Adjusted
- [x] Tailhook Hinge Unwrapped
- [x] Wheel Well Launch Hooks Unwrapped
- [x] External light animations adjusted
- [x] Small unwrap edits around probe
