### ISSUE TITLE
2.3 kneeboard edit to-do list

### ISSUE THREAD

**Issue by callmepartario** [Community-A-4E/community-a4e-c#653]
# quick fixes
- [x] **5-2** - fixes from drofseh (see comments below)
- [x] **5-7** - correct "Sttitudes" to "Altitudes"

# 1-5
- [x] add shrike seeker head keybind notes
- Q: can we set the seeker head after a re-arm on the kneeboard as "unknown" (maybe print it in red)? this could prevent any mismatches, and would provide a complete lack of tone unless seeker heads were at least set to *something*.

# 3-5
- [x] Condense gun performance altitude-scale to half size.

# 3-6 (new Shrike page)
- [x] Armed AGM-45s seek and fire in station order: 1, 5, 2, 4
- [x] Seeker heads can be set in the mission editor. If you rearm, confirm the seeker in your loadout before takeoff - 1-5
- [x] Add seeker heads vs. corresponding radars
- [ ] Confirm SEAD instant action mission assigns proper seeker heads for SAM units the player is expected to destroy.

# 3-7
- [x] update page 3-6 references across manual to new page ID

# 5-3
- [x] corrected spoiler switch instruction in takeoff checklist #645 

# other
- [ ] illumination rockets - how far/long do they travel before illumination
- [ ] CBU info redux? anything different to note, or deployment notes to add?

# binaries
- [x] add page 3-7 to lua pages
- [x] all kneeboard page images updated
- [x] PDF manual updated

**Comment by Drofseh** [comment]
Pre-Taxi 9. B. Check Angle Reading

`121 0 ± 2°` should be `0 ± 2°`

**Comment by Drofseh** [comment]
Pre-Taxi 13. B. Night CVN

I believe `Excepting LANDING LIGHT` should be `Excepting TAXI LIGHT`

**Comment by callmepartario** [comment]
thanks, will add this on my to-do.

**Comment by callmepartario** [comment]
closing this in anticipation of release. all accounted for.
